# Generated by Django 3.2.9 on 2021-11-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='website',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
